In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import numpy as np


In [3]:
a2=np.array([[1,3,4],[4,9,0]])
a2

array([[1, 3, 4],
       [4, 9, 0]])

In [4]:
a2.shape

(2, 3)

In [5]:
a2.ndim

2

In [6]:
a2.size

6

In [7]:
a3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[11,12,13]]])

In [8]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [11, 12, 13]]])

In [9]:
a3.size


12

In [10]:
a3.ndim


3

In [11]:
a3.shape

(2, 2, 3)

In [12]:
type(a3)

numpy.ndarray

In [13]:
a3.dtype

dtype('int64')

In [14]:
one=np.ones([2,2],dtype=np.int32)

In [23]:
one


array([[1, 1],
       [1, 1]], dtype=int32)

In [15]:
zero=np.zeros([2,2])

In [16]:
zero

array([[0., 0.],
       [0., 0.]])

In [17]:
range= np.arange(0,10,2)

In [18]:
range

array([0, 2, 4, 6, 8])

In [24]:
# Random Number
array_random = np.random.randint(0,10,size=(3,3))

In [25]:
array_random

array([[7, 7, 0],
       [4, 2, 2],
       [7, 7, 9]])

In [23]:
array_random.size

9

In [28]:
array_random2= np.random.random((3,3))

In [29]:
array_random2


array([[0.35996492, 0.05164113, 0.61066451],
       [0.07971286, 0.73767857, 0.23388557],
       [0.04740032, 0.57721723, 0.50214877]])

In [30]:
array_random2.dtype

dtype('float64')

In [31]:
array_random.dtype

dtype('int64')

In [32]:
array_random3=np.random.rand(3,3)


In [33]:
array_random3

array([[0.64164761, 0.52832146, 0.82871409],
       [0.95979172, 0.50897545, 0.77025299],
       [0.62794509, 0.2207103 , 0.37224726]])

In [34]:
array_random3.dtype

dtype('float64')

In [35]:
array_random

array([[7, 7, 0],
       [4, 2, 2],
       [7, 7, 9]])

In [37]:
np.unique(array_random)

array([0, 2, 4, 7, 9])

In [38]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [11, 12, 13]]])

In [40]:
a2

array([[1, 3, 4],
       [4, 9, 0]])

In [41]:
a2[0]

array([1, 3, 4])

In [48]:
a2[0][:2]

array([1, 3])

In [42]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
a3[0][:2,:2]

array([[1, 2],
       [4, 5]])

In [52]:
a4=np.random.randint(10,size=(2,3,3))

In [53]:
a4

array([[[1, 5, 1],
        [0, 4, 5],
        [1, 3, 7]],

       [[3, 0, 8],
        [7, 9, 4],
        [8, 4, 9]]])

In [54]:
a4[0]

array([[1, 5, 1],
       [0, 4, 5],
       [1, 3, 7]])

In [56]:
a4[0][:2,:2]

array([[1, 5],
       [0, 4]])

In [57]:
a4[:1,:2,:2]

array([[[1, 5],
        [0, 4]]])

In [58]:
a4[1][:2,:2]

array([[3, 0],
       [7, 9]])

In [60]:
a4[1,:2,:2]

array([[3, 0],
       [7, 9]])

In [61]:
a5=np.random.randint(10,size=(2,3,4,5))


In [62]:
a5

array([[[[3, 1, 7, 3, 5],
         [4, 0, 6, 5, 6],
         [5, 1, 3, 4, 9],
         [4, 6, 5, 3, 8]],

        [[2, 2, 3, 2, 4],
         [2, 7, 9, 9, 1],
         [0, 3, 1, 5, 5],
         [6, 2, 3, 5, 7]],

        [[7, 0, 7, 9, 4],
         [4, 0, 1, 2, 3],
         [0, 0, 1, 1, 8],
         [2, 5, 9, 1, 8]]],


       [[[4, 4, 7, 4, 5],
         [4, 2, 2, 8, 0],
         [7, 9, 0, 3, 7],
         [1, 0, 8, 0, 1]],

        [[5, 3, 0, 3, 7],
         [4, 2, 5, 7, 8],
         [7, 3, 9, 1, 3],
         [2, 6, 6, 2, 1]],

        [[8, 7, 9, 7, 2],
         [0, 0, 3, 4, 4],
         [1, 1, 0, 0, 5],
         [9, 0, 9, 5, 9]]]])

In [63]:
a5[:1,:3,:3,:3]

array([[[[3, 1, 7],
         [4, 0, 6],
         [5, 1, 3]],

        [[2, 2, 3],
         [2, 7, 9],
         [0, 3, 1]],

        [[7, 0, 7],
         [4, 0, 1],
         [0, 0, 1]]]])

In [65]:
a5[:,:,:1,:]

array([[[[3, 1, 7, 3, 5]],

        [[2, 2, 3, 2, 4]],

        [[7, 0, 7, 9, 4]]],


       [[[4, 4, 7, 4, 5]],

        [[5, 3, 0, 3, 7]],

        [[8, 7, 9, 7, 2]]]])