# Introduction to Scikit-Learn (sklearn)

This notebook demonstrates some of the most useful functions of the beautiful Scikit-Learn library.

What we're going to cover:

# Let's listify the contents
what_were_covering = [
  
    "0. An end-to-end Scikit-Learn workflow",
    "1. Getting the data ready",
    "2. Choose the right estimator/algorithm for our problems",
    "3. Fit the model/algorithm and use it to make predictions on our data",
    "4. Evaluating a model",
    "5. Improve a model",
    "6. Save and load a trained model",
    "7. Putting it all together!"]

In [102]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [105]:
import numpy as np

In [ ]:
# Igonre all Warning thta my be happen in this project
import warnings
warnings.filterwarnings("ignore")

In [ ]:
# show version of scklearn
import sklearn
sklearn.show_versions()

In [106]:
# "1. Getting the data ready"
import pandas as pd
heart_disease = pd.read_csv("/content/drive/MyDrive/ML_project/heart-disease.csv")
heart_disease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [ ]:
# Create X(Features Matrix)
X=heart_disease.drop("target",axis=1)
# Create Y(labels)
y=heart_disease["target"]

In [ ]:
# In this problem we use classification models
# 2. Choose the right estimator/algorithm for our problems
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier()
# We'll keep the default parameters
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [ ]:
# 3. Fit the model/algorithm and use it to make predictions on our data
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [ ]:
clf.fit(X_train,y_train)

RandomForestClassifier()

In [ ]:
y_predds= clf.predict(X_test)
y_predds

array([1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1])

In [ ]:
# 4. Evaluating a model on the training and testing data
# training
clf.score(X_train,y_train)

1.0

In [ ]:
# Test
clf.score(X_test,y_test)

0.819672131147541

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
print(classification_report(y_test,y_predds))

              precision    recall  f1-score   support

           0       0.91      0.69      0.78        29
           1       0.77      0.94      0.85        32

    accuracy                           0.82        61
   macro avg       0.84      0.81      0.81        61
weighted avg       0.84      0.82      0.82        61



In [ ]:
confusion_matrix(y_test,y_predds)

array([[20,  9],
       [ 2, 30]])

In [ ]:
accuracy_score(y_test,y_predds)

0.819672131147541

In [ ]:
# 5.Improve The Model
# Try using different amount of n_estimators
np.random.seed(42)
for i in range(100, 200, 10):
    print(f"Trying model with {i} estimators...")
    model = RandomForestClassifier(n_estimators=i).fit(X_train, y_train)
    print(f"Model accuracy on test set: {model.score(X_test, y_test) * 100:.2f}%")
    print("")

Trying model with 100 estimators...
Model accuracy on test set: 85.25%

Trying model with 110 estimators...
Model accuracy on test set: 81.97%

Trying model with 120 estimators...
Model accuracy on test set: 81.97%

Trying model with 130 estimators...
Model accuracy on test set: 83.61%

Trying model with 140 estimators...
Model accuracy on test set: 80.33%

Trying model with 150 estimators...
Model accuracy on test set: 85.25%

Trying model with 160 estimators...
Model accuracy on test set: 81.97%

Trying model with 170 estimators...
Model accuracy on test set: 83.61%

Trying model with 180 estimators...
Model accuracy on test set: 83.61%

Trying model with 190 estimators...
Model accuracy on test set: 81.97%



In [ ]:
# 6. Save a model and Load it
import pickle
pickle.dump(clf,open("/content/drive/MyDrive/ML_project/random_forest_model_1.pkl","wb"))



# **1.   Getting the data ready**




Data doesn't always come ready to use with a Scikit-Learn machine learning model.

Four of the main steps you'll often have to take are:



*   Splitting the data into features (usually X) and labels (usually y).
*   Splitting the data into training and testing sets (and possibly a validation set).

*   Filling (also called imputing) or disregarding missing values.
*   Converting non-numerical values to numerical values (also call feature encoding).









In [ ]:
# Splitting the data into X & y
heart_disease.head()


age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [ ]:
# Splitting the data into features (X) and labels (y)
X = heart_disease.drop('target', axis=1)
X

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  
0        0   0     1  
1        0   0     2  
2        2   0     2  
3        2   0     2  
4        2   0     2  
..     ...  ..   ...  
298      1   0     3  
299      1   0     3  
300      1   2     3  
301      1   1     3  
302      1   1     2  

[303 rows x 13 columns]

In [ ]:
y = heart_disease['target']
y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.2)

In [ ]:
X_train.shape , X_test.shape , y_train.shape , y_test.shape

((242, 13), (61, 13), (242,), (61,))

In [ ]:
car_sales = pd.read_csv('/content/drive/MyDrive/ML_project/car-sales-extended.csv')
car_sales.head()

Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [ ]:
car_sales.shape

(1000, 5)

In [ ]:
car_sales.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price             int64
dtype: object

In [ ]:
# Split into X and Y
X=car_sales.drop("Price",axis=1)
y=car_sales["Price"]
# Split into training and Testing
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.2)

In [ ]:
# Buid macine learning model
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
# Here we have error beacuse we ml can't with dataset that have type String
# as solution we should convert all column that have type string
model.fit(X_train,y_train)

ValueError: could not convert string to float: 'Nissan'

In [ ]:
# Turn categories into a numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
# and we have convert doors also beacuse this column have only three category
categorical_features = ["Make","Colour","Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot",
                                  one_hot,
                                  categorical_features)],
                                remainder="passthrough")
transformed_X = transformer.fit_transform(X)
transformed_X

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]])

In [ ]:
transformed_X.shape

(1000, 13)

In [ ]:
pd.DataFrame(transformed_X)

0    1    2    3    4    5    6    7    8    9    10   11        12
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1    1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
995  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   35820.0
996  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  155144.0
997  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   66604.0
998  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  215883.0
999  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  248360.0

[1000 rows x 13 columns]

In [ ]:
transformed_X.dtype

dtype('float64')

In [ ]:
car_sales["Colour"].value_counts() , car_sales["Doors"].value_counts() , car_sales["Make"].value_counts()

(Colour
 White    407
 Blue     321
 Black     99
 Red       94
 Green     79
 Name: count, dtype: int64,
 Doors
 4    856
 5     79
 3     65
 Name: count, dtype: int64,
 Make
 Toyota    398
 Honda     304
 Nissan    198
 BMW       100
 Name: count, dtype: int64)

In [ ]:
dummies = pd.get_dummies(car_sales[["Make","Colour","Doors"]],dtype=int)
dummies

Doors  Make_BMW  Make_Honda  Make_Nissan  Make_Toyota  Colour_Black  \
0        4         0           1            0            0             0   
1        5         1           0            0            0             0   
2        4         0           1            0            0             0   
3        4         0           0            0            1             0   
4        3         0           0            1            0             0   
..     ...       ...         ...          ...          ...           ...   
995      4         0           0            0            1             1   
996      3         0           0            1            0             0   
997      4         0           0            1            0             0   
998      4         0           1            0            0             0   
999      4         0           0            0            1             0   

     Colour_Blue  Colour_Green  Colour_Red  Colour_White  
0              0             0           0             1  
1              1             0           0             0  
2              0             0           0             1  
3              0             0           0             1  
4              1             0           0             0  
..           ...           ...         ...           ...  
995            0             0           0             0  
996            0             0           0             1  
997            1             0           0             0  
998            0             0           0             1  
999            1             0           0             0  

[1000 rows x 10 columns]

In [ ]:
from sklearn.model_selection import train_test_split
np.random.seed(42)
X_train , X_test , y_train , y_test = train_test_split(transformed_X,y,test_size=0.2)
model.fit(X_train,y_train)

RandomForestClassifier()

In [ ]:
model.score(X_train,y_train)

1.0

In [ ]:
model.score(X_test,y_test)

0.0

In [ ]:
model.predict(X_test)

array([14189,  8834, 24891, 19545, 35004, 12872, 13200, 20130, 18834,
        5125, 22784, 19085, 35432, 13722,  8916, 21326, 14986, 20705,
       31570,  6075, 35004, 13106, 23064, 10494, 35432, 31343, 12408,
       10125, 22784, 21326, 16273, 12146,  7994, 17802, 10125,  6750,
       12988, 29551, 10287,  6720, 18358, 33850, 32566, 13434, 10261,
       25780, 16719, 12732, 31206,  9362,  8952,  9184, 24342,  8952,
        6762, 23438,  2796,  7350,  9224, 22616, 11121, 10628, 34231,
       18180, 15372, 11406, 10494, 29551, 14986, 11731, 14849, 12531,
       17171, 17422,  5101, 14793, 25873, 20705, 11731, 13199,  9734,
        8834,  7823, 33758, 28599, 12218,  3825,  8089, 33198, 23336,
       16909, 25763, 10377,  9545, 14717, 15652, 10429, 13127, 29681,
       19357, 18919, 16519, 13257, 31570, 29959,  6357, 10076,  7882,
       19258,  6197, 20306, 19453,  4358,  5222, 13474, 14650,  6160,
       22784,  6241, 35333, 14086,  6386,  7445,  8179, 14274,  8786,
        8980, 15778,

In [ ]:
prediction_model= model.predict(X_test)

In [ ]:
accuracy_score(y_test,prediction_model)

0.0

# **1.2 - What if we have a missing Values**



1.   ***Fill them with some value (also known as imputation).***
2. ***remove the smaples with missing data altogether.***



In [ ]:
# import missing Data
import pandas as pd

car_sales_missing = pd.read_csv('/content/drive/MyDrive/ML_project/car-sales-extended-missing-data.csv')
car_sales_missing.head()


Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [ ]:
car_sales_missing.shape

(1000, 5)

In [ ]:
# we using this line of code to show us how many missing value or how many rows
car_sales_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [ ]:
X = car_sales_missing.drop('Price', axis=1)
y = car_sales_missing['Price']

In [ ]:
# Turn categories into a numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
# and we have convert doors also beacuse this column have only three category
categorical_features = ["Make","Colour","Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot",
                                  one_hot,
                                  categorical_features)],
                                remainder="passthrough")
transformed_X = transformer.fit_transform(X)
transformed_X
# here er nan value that why show us eroor

<1000x16 sparse matrix of type '<class 'numpy.float64'>'
	with 4000 stored elements in Compressed Sparse Row format>

# option 1 :Fill missing data with **Pandas**

In [ ]:
# Fill the make column
car_sales_missing['Make'].fillna('missing', inplace=True)
# Fill the colour column
car_sales_missing['Colour'].fillna('missing', inplace=True)
# fill the odemeter column
car_sales_missing['Odometer (KM)'].fillna(car_sales_missing['Odometer (KM)'].mean(), inplace=True)
# fill the doors column
car_sales_missing['Doors'].fillna(4, inplace=True)

In [ ]:
car_sales_missing.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [ ]:
# Remove the msising values from the Price column
car_sales_missing.dropna(inplace=True)

In [ ]:
len(car_sales_missing)


950

In [ ]:
X = car_sales_missing.drop('Price', axis=1)
y = car_sales_missing['Price']

In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
# and we have convert doors also beacuse this column have only three category
categorical_features = ["Make","Colour","Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot",
                                  one_hot,
                                  categorical_features)],
                                remainder="passthrough")
transformed_X = transformer.fit_transform(car_sales_missing)
transformed_X

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        3.54310e+04, 1.53230e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        1.92714e+05, 1.99430e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        8.47140e+04, 2.83430e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 0.00000e+00,
        6.66040e+04, 3.15700e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.15883e+05, 4.00100e+03],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.48360e+05, 1.27320e+04]])

In [ ]:
pd.DataFrame(transformed_X)

0    1    2    3    4    5    6    7    8    9    10   11   12   13  \
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0   
1    1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0   
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0   
4    0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
945  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   
946  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0   
947  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   
948  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0   
949  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   

           14       15  
0     35431.0  15323.0  
1    192714.0  19943.0  
2     84714.0  28343.0  
3    154365.0  13434.0  
4    181577.0  14043.0  
..        ...      ...  
945   35820.0  32042.0  
946  155144.0   5716.0  
947   66604.0  31570.0  
948  215883.0   4001.0  
949  248360.0  12732.0  

[950 rows x 16 columns]

# Option 2 : Fill the misssing Value With Scikit-learn

In [76]:
car_sales_missing2 = pd.read_csv('/content/drive/MyDrive/ML_project/car-sales-extended-missing-data.csv')
car_sales_missing2.head()

Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [77]:
car_sales_missing2.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [78]:
car_sales_missing2.dropna(subset=["Price"],inplace=True)
car_sales_missing2.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
Price             0
dtype: int64

In [83]:
# Split into X , y
X = car_sales_missing2.drop('Price', axis=1)
y = car_sales_missing['Price']

In [84]:
# Fill the missing Values with Scikit-learn
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

# Fill Categorical Value with 'missing' & numerical values with maen
categorical_imputer = SimpleImputer(strategy='constant',fill_value='missing')
door_imputer = SimpleImputer(strategy='constant',fill_value=4)
numerical_imputer = SimpleImputer(strategy='mean')

# Define Column
cat_faetures = ['Make','Colour']
door_features = ['Doors']
num_features = ['Odometer (KM)']

# Create an imputer (something tha fills missing Data)
imputer = ColumnTransformer([
                             ('cat_imputer',categorical_imputer,cat_faetures),
                             ('door_imputer',door_imputer,door_features),
                             ('num_imputer',numerical_imputer,num_features)
                             ])

# Transform the data
filled_X = imputer.fit_transform(X)
filled_X

array([['Honda', 'White', 4.0, 35431.0],
       ['BMW', 'Blue', 5.0, 192714.0],
       ['Honda', 'White', 4.0, 84714.0],
       ...,
       ['Nissan', 'Blue', 4.0, 66604.0],
       ['Honda', 'White', 4.0, 215883.0],
       ['Toyota', 'Blue', 4.0, 248360.0]], dtype=object)

In [88]:
car_Sales_failled =pd.DataFrame(filled_X , columns=['Make','Colour','Doors','Odometer (KM)'])

In [89]:
car_Sales_failled

Make Colour Doors Odometer (KM)
0      Honda  White   4.0       35431.0
1        BMW   Blue   5.0      192714.0
2      Honda  White   4.0       84714.0
3     Toyota  White   4.0      154365.0
4     Nissan   Blue   3.0      181577.0
..       ...    ...   ...           ...
945   Toyota  Black   4.0       35820.0
946  missing  White   3.0      155144.0
947   Nissan   Blue   4.0       66604.0
948    Honda  White   4.0      215883.0
949   Toyota   Blue   4.0      248360.0

[950 rows x 4 columns]

In [91]:
car_Sales_failled.isna().sum() , car_Sales_failled.shape

(Make             0
 Colour           0
 Doors            0
 Odometer (KM)    0
 dtype: int64,
 (950, 4))

In [92]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
# and we have convert doors also beacuse this column have only three category
categorical_features = ["Make","Colour","Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot",
                                  one_hot,
                                  categorical_features)],
                                remainder="passthrough")
transformed_X = transformer.fit_transform(car_Sales_failled)
transformed_X

<950x15 sparse matrix of type '<class 'numpy.float64'>'
	with 3800 stored elements in Compressed Sparse Row format>

In [98]:
np.random.seed(42)
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(transformed_X,y,test_size=0.2)
model = RandomForestRegressor()
predict = model.fit(X_train,y_train)
model.score(X_test,y_test)

0.21990196728583944

In [97]:
model.score(X_train,y_train)

0.8845872827949007