In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


#1 - Shossing the Right Model



**Choose the right estimator / algorithme for our problem**

Some Things to Note :


*   sklearn refers to machine learning models , algoritme as estimators
*   classification problem  - predicting a category (heart disease or not)
*   Sometimes you'l see **clf** (shor of classificatin) used as as classification estimator
*   Regression problem -predicting a number (selling price or car )


to shose right model we have see ml map : https://scikit-learn.org/1.3/tutorial/machine_learning_map/index.html













In [2]:
# 2.1 picking a ML model for a regression problem
# we use the california housing Dataset
# Get California Housing Daraset
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing()
housing


{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

In [3]:
import pandas as pd
housing_df = pd.DataFrame(housing["data"]
                          , columns=housing["feature_names"]
                          )
# housing_df["target"] = pd.Series(housing["target"])
housing_df


MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  
0        -122.23  
1        -122.22  
2        -122.24  
3        -122.25  
4        -122.25  
...          ...  
20635    -121.09  
20636    -121.21  
20637    -121.22  
20638    -121.32  
20639    -121.24  

[20640 rows x 8 columns]

In [4]:
housing_df.isna().sum()

MedInc        0
HouseAge      0
AveRooms      0
AveBedrms     0
Population    0
AveOccup      0
Latitude      0
Longitude     0
dtype: int64

In [5]:
housing_df["target"] = housing["target"]


In [6]:
housing_df

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  target  
0        -122.23   4.526  
1        -122.22   3.585  
2        -122.24   3.521  
3        -122.25   3.413  
4        -122.25   3.422  
...          ...     ...  
20635    -121.09   0.781  
20636    -121.21   0.771  
20637    -121.22   0.923  
20638    -121.32   0.847  
20639    -121.24   0.894  

[20640 rows x 9 columns]

In [7]:
# Import algoithms
from sklearn.linear_model import Ridge
import numpy as np
# Setup random seed
np.random.seed(42)

# Create Data
X=housing_df.drop("target",axis=1)
y=housing_df["target"]

# Import train_test_split
from sklearn.model_selection import train_test_split
# plit Data
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

# instantiate and fit the model (on the tarining set)
model = Ridge()
model.fit(X_train,y_train)

# Check the score of the model (on the test data)
model.score(X_test,y_test)


0.5758549611440126

In [9]:
model.score(X_train,y_train)


0.6125511245209703

what if `Ridge` didn't work or the score didn't fit our nedd ?

Well , we could always try different models ...

How about we try ensemble model (an ensemble is combination of smaller model to try and make better prediction than just single prediction)


for exmple `RandomForest` : it's combinaison of lot of decision tree

For Regression we use `sklearn.ensemble.RandomForestRegressor`


In [10]:
# Import RandomForest Regressor model class from the ensemble module
from sklearn.ensemble import RandomForestRegressor
# setup Random sees
np.random.seed(42)
# Create The data
X=housing_df.drop("target",axis=1)
y=housing_df["target"]
# Split the data
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)
# create model forest model
model = RandomForestRegressor()
# fit the model
model.fit(X_train,y_train)
# check the score
model.score(X_test,y_test)

0.8066196804802649

# **2.2 Picking machine learnin model for a classification models**

In [11]:
import pandas as pdm
heart_disease = pd.read_csv("/content/drive/MyDrive/ML_project/heart-disease.csv")
heart_disease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

After we see map and compare with the dataset we have we shose to try LinearSVC


In [12]:
# Import the linearSVC estimator class
from sklearn.svm import LinearSVC

# Setup random seed
np.random.seed(42)

# Make the data
X = heart_disease.drop("target",axis=1)
y = heart_disease["target"]

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

# Instantiate LinearSVC
clf = LinearSVC()

# Fit the model
clf.fit(X_train,y_train)

# Evaluate the LinearSVC
clf.score(X_test,y_test)

/usr/local/lib/python3.10/dist-packages/sklearn/svm/_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


0.8688524590163934

we use EnsembleClassifier

In [13]:
from sklearn.ensemble import RandomForestClassifier

# Setup random seed
np.random.seed(42)

# Make the data
X = heart_disease.drop("target",axis=1)
y = heart_disease["target"]

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

# Instantiate Random Forset Classifier
clf = RandomForestClassifier()

# Fit the model
clf.fit(X_train,y_train)

# Evaluate the Random Forest Classifier
clf.score(X_test,y_test)

0.8524590163934426

# 3.1 Fitting the model to the data


1.   Fit the model /algorithme and use it to me predection on our data




1.  `X` = Features , features variable , data
2.   `y` = labels , targets , target variable










In [14]:
from sklearn.ensemble import RandomForestClassifier

# Setup random seed
np.random.seed(42)

# Make the data
X = heart_disease.drop("target",axis=1)
y = heart_disease["target"]

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

# Instantiate Random Forset Classifier
clf = RandomForestClassifier()

# Fit the model(training machine learning model)
clf.fit(X_train,y_train)

# Evaluate the Random Forest Classifier (use te patterns that has learn)
clf.score(X_test,y_test)

0.8524590163934426

# ***3.2 make predictions using a machine learning model***

2 ways to meke prediction



1.   `predict()`: guve single lable of each each simple
2.   `predict_proba()`: retun proba of classification labels




In [15]:
# 1 - make prediction with predict()
clf.predict(X_test)

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [16]:
np.array(y_test)

array([0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [17]:
# Compare predictions to truth labels to evaluate the model
y_predicts = clf.predict(X_test)
np.mean(y_predicts == y_test)

0.8524590163934426

In [18]:
clf.score(X_test,y_test)

0.8524590163934426

In [19]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_predicts)


0.8524590163934426

2. Make Prediction with `predict_proba()`

`predict_proba()` return probabilities of classification labels

In [20]:
clf.predict_proba(X_test[:5])

array([[0.89, 0.11],
       [0.49, 0.51],
       [0.43, 0.57],
       [0.84, 0.16],
       [0.18, 0.82]])

In [21]:
# let's predict() on the same data
clf.predict(X_test[:5])

array([0, 1, 1, 0, 1])

In [22]:
heart_disease["target"].value_counts()

target
1    165
0    138
Name: count, dtype: int64

`predict()` can be also use for regression models

In [23]:
from sklearn.ensemble import RandomForestRegressor

# Setup random seed
np.random.seed(42)

# Make the data
X = housing_df.drop("target",axis=1)
y = housing_df["target"]

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

# Instantiate Random Forset Classifier
model = RandomForestRegressor()

# Fit the model(training machine learning model)
model.fit(X_train,y_train)

# make prediction
y_preds = model.predict(X_test)

In [24]:
y_preds[:5]

array([0.49384  , 0.75494  , 4.9285964, 2.54029  , 2.33176  ])

In [26]:
np.array(y_test[:5])

array([0.477  , 0.458  , 5.00001, 2.186  , 2.78   ])

In [27]:
len(y_preds) , len(y_test)

(4128, 4128)

In [28]:
# Compare the prediction to the truth
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test,y_preds)

0.3265721842781009